-- Generated by tools/build_statics.py -- do not hand-edit.
--
-- The static overworld encounters, keyed by map. A row is
-- { species, vanillaLevel, level, moves }.
--
-- vanillaLevel is the match key, not decoration: static_battles.lua
-- recognises one of these by the triple (map, species, the level the
-- script asked for). Matching on species and level alone would break
-- the moment a level moves -- Electrode at 50 collides with the wild
-- Electrode in Cerulean Cave, and Marowak appears wild at 40, 43, 52
-- and 55.
--
-- Not keyed by game version, unlike boss_teams.lua. Party indices are
-- what forced that; the static scripts are shared by Red, Blue and
-- Yellow alike, and the builder validates this one table against all
-- three.
return {
  ["CERULEAN_CAVE_B1F"] = {
    -- Blizzard is for the other Psychics, which are all Psychic resists
    { "MEWTWO", 70, 85, { "PSYCHIC_M", "AMNESIA", "RECOVER", "BLIZZARD" } },
  },
  ["POKEMON_TOWER_6F"] = {
    -- uncatchable story wall; grinds you down rather than bursting you
    { "MAROWAK", 30, 46, { "EARTHQUAKE", "BODY_SLAM", "ICE_BEAM", "TOXIC" } },
  },
  ["POWER_PLANT"] = {
    -- six of these; Selfdestruct stings rather than deletes off 30 Attack
    { "VOLTORB", 40, 46, { "THUNDERBOLT", "SWIFT", "THUNDER_WAVE", "SELFDESTRUCT" } },
    -- two of these; 170 power off the fastest thing in the game
    { "ELECTRODE", 43, 50, { "THUNDERBOLT", "SWIFT", "THUNDER_WAVE", "EXPLOSION" } },
    -- Hyper Beam is its answer to Ground; Agility takes 100 speed to 200
    { "ZAPDOS", 50, 70, { "THUNDERBOLT", "DRILL_PECK", "HYPER_BEAM", "AGILITY" } },
  },
  ["ROUTE_12"] = {
    -- the brawler: paralysis, and Rock Slide for what shrugs off Ground
    { "SNORLAX", 30, 48, { "BODY_SLAM", "EARTHQUAKE", "ROCK_SLIDE", "AMNESIA" } },
  },
  ["ROUTE_16"] = {
    -- the same Pokemon four levels past Double-Edge, hitting accordingly
    { "SNORLAX", 30, 52, { "DOUBLE_EDGE", "EARTHQUAKE", "ROCK_SLIDE", "AMNESIA" } },
  },
  ["SEAFOAM_ISLANDS_B4F"] = {
    -- 10% freeze is permanent in Gen 1 without a Fire move or an Ice Heal
    { "ARTICUNO", 50, 70, { "BLIZZARD", "ICE_BEAM", "HYPER_BEAM", "REFLECT" } },
  },
  ["VICTORY_ROAD_2F"] = {
    -- the last thing between the player and the Elite Four
    { "MOLTRES", 50, 70, { "FIRE_BLAST", "HYPER_BEAM", "DOUBLE_EDGE", "AGILITY" } },
  },
}
